### PR TITLE
Add PDF of ALFRESCO Guide to docs

### PR DESCRIPTION
**Pull request by cstephen**
This PR simply adds an "ALFRESCO Guide" PDF file to the `docs` directory. This is based on a 5-year-old draft document that was fixed up to:

- Remove draft language and inline draft questions
- Update years to reflect that we are now using ALFRESCO Master Dataset v2.1, which uses CRU TS 4.0 historical data up to 2015 (formerly 2009), and projected model output starts in 2016 (formerly 2010).
- Update broken links
- Remove outdated references to "ongoing development"

To test, read through the PDF and make sure it looks up-to-date and not drafty.

### CODE REVIEW

**Review by kyleredilla — CHANGES_REQUESTED** [review]
This looks great! I think it is fine to merge this in as is, but I had some comments for things to looked odd that I think should get at least a look/consideration first. Here are my notes (can't do comments on the binary file):

Maybe the URL changed for the "GTOPO30" hyperlink in the "inputs" section? This looks like a better page for it compared to the current version: https://www.usgs.gov/centers/eros/science/usgs-eros-archive-digital-elevation-global-30-arc-second-elevation-gtopo30

Wondering about this snippet in the model inputs section as well: "Climate (temperature, precipitation) is based on downscaled observed historical data (high-resolution CRU data), or downscaled future climate projections (SNAP)." It seems odd to call reference the future climate projections as "(SNAP)" when the CRU data are downscaled by us as well. Also the resolution of both inputs are the same so it seems odd to refer to only CRU as being "high resolution" I would suggest something like: 

"Climate (temperature, precipitation) is based on observed historical data (CRU TS), or future climate projections (CMIP5), both statistically downscaled to 1km by SNAP."

I don't understand third bullet point of "Vegetation Succession Loops" section ("Probabilities: a * age + b"). 

In the PHASE 1 section, wondering about the "800 years of spin-up" - should it be 900 years of spin-up, if it goes from 1000-1900?

In the "ALFRESCO Model Phases" section I noticed many of the outputs show only the number of maps per year, instead of total number of maps (i.e. maps x years). Consider adding language to clarify that those counts are per year, or listing the total numbers of maps for each phase after multiplying by number of years? Also, on that note, noticed that there are 200 veg type and veg age maps, but that number isn't given for the three other categories (fire scar, basal area, burn severity) - should those be 200 as well? Or the same as those first two categories, if changed.

**Comment by cstephen** [comment]
I've made a bunch of changes to the ALFRESCO Guide PDF in my latest commit. These include changes to incorporate @kyleredilla's suggestions:

- The GTOP30 link has been updated to point to https://www.usgs.gov/centers/eros/science/usgs-eros-archive-digital-elevation-global-30-arc-second-elevation-gtopo30
- We are now using Kyle's suggested text to clarify that both the historical and projected climate data have been downscaled to 1km by SNAP.
- The spin-up section has been updated to indicate that model spin-up occurs for 900 years, not 800 years.
- Output sections have been updated to indicate that 200 maps of the following types are generated for each year (historical) or year/model/scenario (projected):
  - Vegetation type
  - Vegetation age
  - Fire scars
  - Basal area
  - Burn severity


I also didn't quite understand what this meant under the "Vegetation Succession Loops" section:

> Probabilities: a * age + b

I dug into the code enough to see how this works so I could write a suitable explanation. Here's the relevant code that shows how this equation is used to determine if Deciduous becomes White Spruce, for example:

https://github.com/ua-snap/alfresco/blob/827e9833bf0e6864e26caea9be48aaa2df8a0f37/src/Decid.cpp#L262-L269

And this chunk of documentation from the `JSONConfig.md` file shows where the a and b values are specified:

```
// The following 8 fields are sets of two coefficients, {A, B}, used
// depending on the trajectory and last burn severity of the given decid
// cell. The chosen values are used in a linear function relating age to
// the probability of transitioning to white or black spruce: A*Age + B.
"WSpruce.BurnSeverity[1]": [0.001000000, -0.07500000],
"WSpruce.BurnSeverity[2]": [0.001000000, -0.07500000],
"WSpruce.BurnSeverity[3]": [0.001000000, -0.09000000],
"WSpruce.BurnSeverity[4]": [0.001000000, -0.09000000],
"BSpruce.BurnSeverity[1]": [0.001428571, -0.07142857],
"BSpruce.BurnSeverity[2]": [0.001428571, -0.07142857],
"BSpruce.BurnSeverity[3]": [0.001000000, -0.07500000],
"BSpruce.BurnSeverity[4]": [0.001000000, -0.07500000]
```

Finally, I also rewrote the chunk of the guide that talked about calibrating model runs by choosing the replicate that matches historical fires most closely. My understanding is that the calibration process was done every handful of years to find sane input parameters for the JSON configuration file and, once discovered, the same input parameters have been used for all subsequent model runs. Calibrating against historical fires is not a routine part of every model run, and we are now incorporating actual historical fires into each model run, so the old text was confusing and unnecessary.

**Review by kyleredilla — APPROVED** [review]
These changes look good - I approve!

**Review by charparr — APPROVED** [review]
This is a great user guide! I like the updated links with data sources and GeoNetwork entries. Perfect ALFRESCO 101 doc with just the right level of detail for data users.

**Pull request merged**
